name: 构建和发布

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    
    steps:
      - name: 安装基础工具
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential rpm curl wget git

      - name: 安装 Go
        run: |
          curl -L https://go.dev/dl/go1.21.6.linux-amd64.tar.gz -o go.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ssl-web

      - name: 安装 nFPM
        run: |
          export PATH=$PATH:/usr/local/go/bin
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: 获取版本号
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: 生成发布说明
        id: release_notes
        run: |
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "## 新版本发布 ${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "### 优化" >> $GITHUB_OUTPUT
          echo "- 优化构建环境，使用 Ubuntu 20.04 LTS 作为基础环境" >> $GITHUB_OUTPUT
          echo "- 改进构建流程，简化依赖安装" >> $GITHUB_OUTPUT
          echo "- 优化包构建配置" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "### 修复" >> $GITHUB_OUTPUT
          echo "- 修复构建环境依赖问题" >> $GITHUB_OUTPUT
          echo "- 改进系统兼容性" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 构建项目
        run: |
          export PATH=$PATH:/usr/local/go/bin
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=amd64
          chmod +x build.sh
          ./build.sh

      - name: 创建打包目录
        run: |
          mkdir -p build
          cp ssl-chain-analyzer build/
          mkdir -p build/assets/web
          cp -r assets/web/* build/assets/web/
          chmod +x packaging/scripts/*.sh

      - name: 打包 RPM
        run: |
          export PATH=$PATH:/usr/local/go/bin:$(go env GOPATH)/bin
          nfpm package --config packaging/nfpm.yaml --target build --packager rpm

      - name: 打包 DEB
        run: |
          export PATH=$PATH:/usr/local/go/bin:$(go env GOPATH)/bin
          nfpm package --config packaging/nfpm.yaml --target build --packager deb

      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: ${{ steps.release_notes.outputs.NOTES }}
          files: |
            build/*.deb
            build/*.rpm
            ssl-chain-analyzer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 配置 Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 更新 CHANGELOG
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.get_version.outputs.VERSION }}
          release-notes: ${{ steps.release_notes.outputs.NOTES }}

      - name: 提交 CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ssl-web
          commit_message: "docs: 更新 CHANGELOG"
          file_pattern: CHANGELOG.md
          repository: .
