name: 安全扫描

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # 每周日运行

jobs:
  security:
    name: 安全扫描
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Go环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: 运行Gosec安全扫描器
        uses: securego/gosec@master
        with:
          args: ./...

      - name: 运行Go漏洞扫描
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.21'
          check-latest: true

      - name: 运行依赖审查
        uses: actions/dependency-review-action@v3
        if: github.event_name == 'pull_request' 